name: 'esnupi.me Post Next Image'

on:
  workflow_dispatch:
  schedule:
    - cron: "50 * * * *"

jobs:
  post-next-image:
    name: Post Next Image
    runs-on: ubuntu-latest
    permissions:
      actions: write
      contents: read
    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          sparse-checkout: |
            /*
            !imagequeue
          sparse-checkout-cone-mode: false
          fetch-depth: 1

      - name: Setup Node.js
        uses: actions/setup-node@v6
        with:
          node-version: 20
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install --immutable

      - name: Poast!
        env:
          NODE_OPTIONS: "--no-deprecation"
          BSKY_IDENTIFIER: ${{ secrets.BSKY_IDENTIFIER }}
          BSKY_PASSWORD: ${{ secrets.BSKY_PASSWORD }}
          GH_TOKEN: ${{ secrets.REPO_ACCESS_TOKEN }}
        run: |
          HISTORY_LIST=$(gh variable get LAST_IMAGE_NAME || echo "")
          echo "scanning catalogue..."
          ALL_IMAGES=$(git ls-tree -r HEAD:imagequeue --name-only)
          SELECTED_IMAGE=$(echo "$ALL_IMAGES" | grep -vFf <(echo "$HISTORY_LIST" | tr ',' '\n') | shuf -n 1)
          if [ -z "$SELECTED_IMAGE" ]; then
            echo "FATAL: you fucked it"
            exit 1
          fi
          echo "your lucky RNG pull of the hour: $SELECTED_IMAGE"
          mkdir -p imagequeue
          git sparse-checkout add "/imagequeue/$SELECTED_IMAGE"
          git checkout "imagequeue/$SELECTED_IMAGE"
          export IMAGE_TO_POST="imagequeue/$SELECTED_IMAGE"
          yarn --silent run start
          echo "" # Corrected output line break
          NEW_HISTORY=$(echo "$SELECTED_IMAGE,$HISTORY_LIST" | tr ',' '\n' | grep -v '^$' | head -n 24 | paste -sd "," -)
          echo "updating the no-no list..."
          gh variable set LAST_IMAGE_NAME --body "$NEW_HISTORY"